### ISSUE TITLE
Extra output in file when running xmlmerge

### ISSUE THREAD

**Issue by jrbeilke** [kirankotari/xmlmerge#10]
Using xmlmerge to combine multiple junit test reports into a single file, but the combined file has extra text in it.

Here's an example of two of the junit files I'm attempting to merge:
```
<testsuites>
  <testsuite name="AWS" tests="23" errors="0" failures="2" skipped="1">
  ...
  </testsuite>
</testsuites>
```

```
<testsuites>
  <testsuite name="K8s" tests="89" errors="0" failures="0" skipped="3">
  ...
  </testsuite>
</testsuites>
```

The xmlmerge command being run:
`xmlmerge results/*.xml > junit2.xml`

And here is the resulting output file from xmlmerge with extra `None` text at the end:
```
<testsuites>
  <testsuite name="AWS" tests="23" errors="0" failures="2" skipped="1">
  ...
  </testsuite>
  <testsuite name="K8s" tests="89" errors="0" failures="0" skipped="3">
  ...
  </testsuite>
</testsuites>
None
```

**Comment by odisseus** [comment]
In fact, the tool doesn't work correctly even for the test example that's included with the project. Here's what I got for commit 7aad44484c5092d900f0825c82a45910d7fb73a2 (Windows 10, Python 3.12):
```
 .\.venv\Scripts\xmlmerge.exe .\tests\file1.xml .\tests\file2.xml
<products>
    <product id="9999">
        <a>1234</a>
        <b>1234</b>
    </product>
<product id="5678">
        <a>1234</a>
        <b>1234</b>
    </product>
</products>
None
```
