### ISSUE TITLE
command line options not read

### ISSUE THREAD

**Issue by Hipska** [kirankotari/xmlmerge#3]
I don't know if this is because of my setup, but this is what I get from this tool:
```
$ xmlmerge --help
Traceback (most recent call last):
  File "/usr/local/bin/xmlmerge", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/xmlmerge/xmlmerge.py", line 9, in run
    data = ElementTree.parse(filename).getroot()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '--help'
```

Seems like master isn't published on pypi?

**Comment by Hipska** [comment]
Ps, it would be nice if the tool also handled the attributes like here:
https://stackoverflow.com/a/29896847/1861492

**Comment by kirankotari** [comment]
> I don't know if this is because of my setup, but this is what I get from this tool:
> 
> ```
> $ xmlmerge --help
> Traceback (most recent call last):
>   File "/usr/local/bin/xmlmerge", line 8, in <module>
>     sys.exit(run())
>   File "/usr/local/lib/python3.9/site-packages/xmlmerge/xmlmerge.py", line 9, in run
>     data = ElementTree.parse(filename).getroot()
>   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
>     tree.parse(source, parser)
>   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
>     source = open(source, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '--help'
> ```
> 
> Seems like master isn't published on pypi?

We are not sure how you have installed, the library if available in pypi, current version is 1.1.1, have a look and let us know if you are facing the same issue again.

**Comment by kirankotari** [comment]
> Ps, it would be nice if the tool also handled the attributes like here: https://stackoverflow.com/a/29896847/1861492

Let me add this in next release.

**Comment by kirankotari** [comment]
I have move this topic to discussion to add these new attributes to xmlmerge or further more data. The initial ticket is resolved in latest versions. closing this.
