### ISSUE TITLE
The output of the xmlmerge command appears in the final xml file

### ISSUE THREAD

**Issue by WendkuuniArzouma** [kirankotari/xmlmerge#4]
Hello, when I tried to use this command `xmlmerge tests/*.xml > combine.xml`, in the combine.xml file there is also this text which appear : 
"xml files planning to merge are: 
['result1.xml', 'result2.xml', 'result3.xml']"

I have just download the latest version :  xmlmerge 1.1.1 with the Pypi installation on a mac computer.

With V1.1.0 it works very well.

**Comment by kirankotari** [comment]
oh shit, got it. Looks like it overlapped the logger and shell syntax. let me correct and push latest one.

**Comment by kirankotari** [comment]
@WendkuuniArzouma done, download the latest version `1.1.2`

**Comment by WendkuuniArzouma** [comment]
Thanks a lot!
Great job!
